
setwd("/home/jorge/Clases/Estadistica")
load("/home/jorge/Downloads/23-24GR evaluaciÃ³n continua global.xlsx")
Dataset <- readXL("/home/jorge/Downloads/23-24GR evaluaciÃ³n continua global.xlsx", rownames=FALSE, header=TRUE, na="", sheet="PUNTOS", stringsAsFactors=TRUE)
Boxplot( ~ puntosProgramaB, data=Dataset, id=list(method="y"))
Boxplot( ~ puntosProgramaC, data=Dataset, id=list(method="y"))
Boxplot(puntosProgramaByC~ProgramaByC, data=Dataset, id=list(method="y"))
library(abind, pos=24)
library(e1071, pos=25)
numSummary(Dataset[,"puntosProgramaByC", drop=FALSE], groups=Dataset$ProgramaByC, statistics=c("mean", "sd", "IQR", "quantiles"), quantiles=c(0,.25,.5,.75,1))
numSummary(Dataset[,"puntosProgramaByC", drop=FALSE], statistics=c("mean", "sd", "IQR", "quantiles"), quantiles=c(0,.25,.5,.75,1))
numSummary(Dataset[,"puntosProgramaC", drop=FALSE], statistics=c("mean", "sd", "IQR", "quantiles"), quantiles=c(0,.25,.5,.75,1))
numSummary(Dataset[,"puntosProgramaB", drop=FALSE], statistics=c("mean", "sd", "IQR", "quantiles"), quantiles=c(0,.25,.5,.75,1))
fivenum(Dataset[,"puntosProgramaByC", drop=FALSE])
fivenum(Dataset[,"puntosProgramaB", drop=FALSE])
fivenum(Dataset[,"puntosProgramaC", drop=FALSE])
RegModel.1 <- lm(bateriaByC~puntosProgramaByC, data=Dataset)
summary(RegModel.1)
load("/home/jorge/Downloads/23-24GR Estatistica - Tema 5 problema 12  RESOLUCION.pdf")
Dataset <- readXL("/home/jorge/Downloads/23-24GR evaluaciÃ³n continua global.xlsx", rownames=FALSE, header=TRUE, na="", sheet="APRENDIZAJE", stringsAsFactors=TRUE)
with(Dataset, (t.test(eficacia18, eficacia12, alternative='two.sided', conf.level=.95, paired=TRUE)))
qt(c(95), df=7, lower.tail=TRUE)
qt(c(0.95), df=7, lower.tail=TRUE)
local({
  .x <- seq(-5.408, 5.408, length.out=1000)  
  plotDistr(.x, dt(.x, df=7), cdf=FALSE, xlab="x", ylab="Density", main=paste("t Distribution:  Degrees of freedom=7"))
})

